import { QuizQuestion } from './quiz-types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ─── PHASE 1: SLEEP BASELINE ─────────────────────────────────────────────
  {
    id: 'q1_sleep_quality',
    phase: 1,
    text: 'How would you describe your sleep quality lately?',
    type: 'single',
    options: [
      { id: 'great', emoji: '😴', text: 'I fall asleep easily and wake up refreshed' },
      { id: 'wake_night', emoji: '🌙', text: 'I fall asleep OK, but wake up during the night' },
      { id: 'hard_fall', emoji: '⏰', text: 'It takes me 30+ minutes to fall asleep most nights' },
      { id: 'rarely_restful', emoji: '😵', text: "I rarely get restful sleep, no matter what I try" },
    ],
  },
  {
    id: 'q2_sleep_barriers',
    phase: 1,
    text: 'What usually prevents you from falling asleep?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'racing_thoughts', emoji: '🧠', text: 'Racing thoughts or mental chatter' },
      { id: 'anxiety', emoji: '😰', text: 'Worry or anxiety about tomorrow' },
      { id: 'screens', emoji: '📱', text: 'Screen time too close to bedtime' },
      { id: 'caffeine', emoji: '☕', text: 'Caffeine or other stimulants' },
      { id: 'tension', emoji: '😣', text: 'Physical tension or discomfort' },
      { id: 'environment', emoji: '🛏️', text: 'Uncomfortable sleep environment (noise, light, temperature)' },
      { id: 'no_reason', emoji: '🤷', text: "No specific reason — my body just won't shut down" },
      { id: 'none', emoji: '✅', text: 'None of these — I fall asleep easily' },
    ],
  },
  {
    id: 'q3_wake_up_experience',
    phase: 1,
    text: 'How do you typically feel when you wake up?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'refreshed', emoji: '⚡', text: 'Refreshed and ready for the day' },
      { id: 'tired', emoji: '😪', text: 'Tired, like I need more sleep' },
      { id: 'groggy', emoji: '🥴', text: 'Groggy or foggy-headed' },
      { id: 'irritable', emoji: '😤', text: 'Irritable or on edge' },
      { id: 'sore', emoji: '💪', text: 'Physically sore or tense' },
      { id: 'coffee_dependent', emoji: '☕', text: 'Completely dependent on coffee to function' },
      { id: 'inconsistent', emoji: '🔁', text: 'Inconsistent — varies day to day' },
    ],
  },

  // ─── PHASE 2: STRESS & LIFESTYLE ──────────────────────────────────────────
  {
    id: 'q4_emotional_baseline',
    phase: 2,
    text: 'During the day, you usually feel...',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'calm', emoji: '😌', text: 'Calm and in control' },
      { id: 'stressed', emoji: '😰', text: 'Stressed or overwhelmed' },
      { id: 'low_energy', emoji: '😔', text: 'Down or low energy' },
      { id: 'irritable', emoji: '😠', text: 'Irritable or short-tempered' },
      { id: 'racing_mind', emoji: '🤯', text: 'Like your mind is racing all the time' },
      { id: 'anxious', emoji: '😟', text: 'Worried or anxious (even without a specific reason)' },
      { id: 'mood_swings', emoji: '🔄', text: 'All over the place — mood changes frequently' },
      { id: 'balanced', emoji: '🙂', text: 'Pretty balanced overall' },
    ],
  },
  {
    id: 'q5_stress_triggers',
    phase: 2,
    text: 'Your daily stress usually comes from...',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'work', emoji: '💼', text: 'Work demands and deadlines' },
      { id: 'family', emoji: '👨‍👩‍👧', text: 'Family or relationship responsibilities' },
      { id: 'financial', emoji: '💰', text: 'Financial pressures' },
      { id: 'no_time', emoji: '🏃', text: 'Not enough time for myself' },
      { id: 'overthinking', emoji: '🤔', text: 'Overthinking and worrying about the future' },
      { id: 'health', emoji: '😷', text: "Health concerns (my own or a loved one's)" },
      { id: 'schedule', emoji: '🗓️', text: 'Overpacked schedule with no downtime' },
      { id: 'digital', emoji: '📱', text: 'Constant notifications and digital overload' },
      { id: 'unsure', emoji: '🤷', text: "I'm not sure — I just feel stressed all the time" },
    ],
  },
  {
    id: 'q6_stress_management',
    phase: 2,
    text: 'How do you usually manage stress?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'meditation', emoji: '🧘', text: 'Yoga or meditation' },
      { id: 'exercise', emoji: '🏃', text: 'Exercise or physical activity' },
      { id: 'hobbies', emoji: '📖', text: 'Reading, journaling, or creative hobbies' },
      { id: 'alcohol', emoji: '🍷', text: 'Wine or other alcohol' },
      { id: 'screens', emoji: '📺', text: 'TV, social media, or scrolling' },
      { id: 'relaxation', emoji: '🛁', text: 'Baths, breathing exercises, or relaxation techniques' },
      { id: 'sleep_it_off', emoji: '😴', text: 'I just try to sleep it off' },
      { id: 'nothing_works', emoji: '🤷', text: "Nothing really works — I can't seem to unwind" },
      { id: 'healthy_coping', emoji: '✅', text: 'I have healthy coping strategies that work well' },
    ],
  },

  // ─── PHASE 3: SYMPTOMS & GOALS ────────────────────────────────────────────
  {
    id: 'q7_symptoms',
    phase: 3,
    text: 'Do you experience any of these symptoms regularly?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'racing_thoughts', emoji: '🧠', text: 'Racing thoughts or mental chatter (especially at night)' },
      { id: 'muscle_tension', emoji: '💪', text: 'Muscle tension, jaw clenching, or tight shoulders' },
      { id: 'heart_racing', emoji: '💓', text: 'Heart racing or feeling on edge' },
      { id: 'headaches', emoji: '🤕', text: 'Headaches or migraines' },
      { id: 'digestive', emoji: '🤢', text: 'Digestive issues (stress stomach, nausea)' },
      { id: 'fatigue', emoji: '😓', text: "Fatigue that doesn't improve with rest" },
      { id: 'temperature', emoji: '🥶', text: 'Cold hands/feet or trouble regulating body temperature' },
      { id: 'numb', emoji: '😶', text: 'Feeling emotionally numb or disconnected' },
      { id: 'none', emoji: '✅', text: 'None of these' },
    ],
  },
  {
    id: 'q8_sleep_goals',
    phase: 3,
    text: 'What are your top sleep goals?',
    type: 'multi-max3',
    hint: 'Select up to 3',
    options: [
      { id: 'fall_faster', emoji: '🛌', text: 'Fall asleep faster (within 20-30 minutes)' },
      { id: 'stay_asleep', emoji: '😴', text: 'Stay asleep through the night (fewer awakenings)' },
      { id: 'wake_refreshed', emoji: '⏰', text: 'Wake up feeling refreshed and energized' },
      { id: 'reduce_anxiety', emoji: '🧘', text: 'Reduce bedtime anxiety or racing thoughts' },
      { id: 'deeper_sleep', emoji: '💤', text: 'Achieve deeper, more restorative sleep' },
      { id: 'natural_wake', emoji: '🌅', text: 'Wake up naturally without an alarm' },
      { id: 'consistent', emoji: '📅', text: 'Get consistent sleep quality (not just occasional good nights)' },
      { id: 'stop_melatonin', emoji: '🙅', text: 'Stop relying on sleep aids or melatonin' },
    ],
  },
  {
    id: 'q9_stress_goals',
    phase: 3,
    text: 'What would better stress management look like for you?',
    type: 'multi-max3',
    hint: 'Select up to 3',
    options: [
      { id: 'calmer', emoji: '😌', text: 'Feel calmer and less reactive throughout the day' },
      { id: 'clear_thinking', emoji: '🧠', text: 'Think more clearly and make decisions without overwhelm' },
      { id: 'mood', emoji: '😊', text: 'Improve my mood and emotional balance' },
      { id: 'energy', emoji: '💪', text: 'Have more energy (not just surviving the day)' },
      { id: 'unwind', emoji: '🧘', text: 'Actually be able to relax and unwind after work' },
      { id: 'no_burnout', emoji: '🗓️', text: 'Handle a busy schedule without burning out' },
      { id: 'sleep_impact', emoji: '😴', text: 'Stop stress from affecting my sleep' },
      { id: 'myself', emoji: '🙂', text: 'Feel like myself again' },
    ],
  },

  // ─── PHASE 4: CURRENT SOLUTIONS ───────────────────────────────────────────
  {
    id: 'q10_previous_attempts',
    phase: 4,
    text: 'What have you already tried for sleep or stress relief?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'melatonin', emoji: '💊', text: 'Melatonin supplements' },
      { id: 'magnesium', emoji: '🧴', text: 'Magnesium supplements (pill, powder, or spray)' },
      { id: 'herbal', emoji: '🍵', text: 'Herbal teas or natural sleep aids' },
      { id: 'prescription_sleep', emoji: '💊', text: 'Prescription sleep medications' },
      { id: 'anxiety_meds', emoji: '🧠', text: 'Anti-anxiety medications' },
      { id: 'apps', emoji: '📱', text: 'Meditation or sleep apps' },
      { id: 'sleep_hygiene', emoji: '📖', text: 'Sleep hygiene changes (dark room, cool temp, etc.)' },
      { id: 'therapy', emoji: '🧘', text: 'Therapy or counseling' },
      { id: 'exercise', emoji: '🏃', text: 'Exercise or lifestyle changes' },
      { id: 'nothing', emoji: '🤷', text: "Nothing yet — I'm just starting to address this" },
      { id: 'tried_a_lot', emoji: '✅', text: "I've tried a lot, but nothing has worked consistently" },
    ],
  },
  {
    id: 'q11_hardest_time',
    phase: 4,
    text: 'When do you struggle the most with stress or sleep issues?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'morning', emoji: '🌅', text: 'Morning — Waking up anxious or dreading the day' },
      { id: 'midday', emoji: '☀️', text: 'Midday — Afternoon energy crashes or stress spikes' },
      { id: 'evening', emoji: '🌆', text: 'Evening — Trouble winding down after work' },
      { id: 'bedtime', emoji: '🌙', text: "Bedtime — Racing thoughts or can't fall asleep" },
      { id: 'middle_night', emoji: '🌃', text: "Middle of the night — Waking up and can't get back to sleep" },
      { id: 'all_day', emoji: '🔄', text: 'All day — Constant stress with no relief' },
    ],
  },

  // ─── PHASE 5: DEMOGRAPHICS ────────────────────────────────────────────────
  {
    id: 'q12_age',
    phase: 5,
    text: "What's your age range?",
    type: 'single',
    options: [
      { id: '18-24', emoji: '', text: '18-24' },
      { id: '25-34', emoji: '', text: '25-34' },
      { id: '35-44', emoji: '', text: '35-44' },
      { id: '45-54', emoji: '', text: '45-54' },
      { id: '55-64', emoji: '', text: '55-64' },
      { id: '65+', emoji: '', text: '65+' },
      { id: 'prefer_not', emoji: '', text: 'Prefer not to say' },
    ],
  },
  {
    id: 'q12_gender',
    phase: 5,
    text: "What's your gender?",
    type: 'single',
    options: [
      { id: 'female', emoji: '', text: 'Female' },
      { id: 'male', emoji: '', text: 'Male' },
      { id: 'nonbinary', emoji: '', text: 'Non-binary' },
      { id: 'prefer_not', emoji: '', text: 'Prefer not to say' },
    ],
  },
  {
    id: 'q12_hormonal',
    phase: 5,
    femaleOnly: true,
    text: 'Do any of these apply to you?',
    type: 'multi',
    hint: 'Select all that apply',
    options: [
      { id: 'pregnant', emoji: '🤰', text: 'Currently pregnant or breastfeeding' },
      { id: 'pms', emoji: '🔴', text: 'I experience PMS or menstrual-related sleep/mood issues' },
      { id: 'menopause', emoji: '🔥', text: "I'm in perimenopause or menopause" },
      { id: 'birth_control', emoji: '💊', text: 'Taking hormonal birth control' },
      { id: 'none', emoji: '✅', text: 'None of these' },
    ],
  },
];
